services:
  postgres:
    image: postgres:13.2-alpine
    container_name: worldcup-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: worldcup
    volumes:
      - worldcup-db-vol:/var/lib/postgresql/data
    networks:
      - monitoring
      - logging

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - db-service
    networks:
      - monitoring

  db-service:
    image: db-service
    ports:
      - "8082:8082"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_URL: jdbc:postgresql://postgres:5432/worldcup
    logging:
      driver: loki
      options:
        loki-url: "http://host.docker.internal:3100/loki/api/v1/push"
    depends_on:
      - postgres
    networks:
      - monitoring
      - logging

  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki.yml:/etc/loki/loki.yml
      - ./wal:/wal
    command: -config.file=/etc/loki/loki.yml
    networks:
      - logging

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki
    networks:
      - monitoring
      - logging

volumes:
  worldcup-db-vol:
  grafana-data:

networks:
  monitoring:
  logging:
